name: 'Set NPM Config'
description: 'Sets the NPMRC file to set the NPM Config files.'
author: 'Mike Burgess'
inputs:
  NPM_FEED_URL:
    description: 'NPM Feed URL'
    required: true
  NPM_PUBLISH_FEED_URL:
    description: 'NPM Publish Feed URL'
    required: true
  NPM_FEED_USER:
    description: 'User name for the NPM feeds'
    required: true
  NPM_FEED_PWD:
    description: 'Password associated with the NPM User for NPM feeds'
    required: true
  NPM_FEED_EMAIL:
    description: 'NPM Feed Email address'
    required: true
  PATH:
    description: 'Relative Path for the location to install NPM, where the NPMRC file will be written.'
    required: false
    
runs:
  using: 'composite'
  steps:
    - run: |
        write-output "writing NPM FEED URL: ${{inputs.NPM_FEED_URL}}"
        ${{ github.action_path }}/../../../Powershell/Scripts\Set-NPMConfig.ps1 -NPMFeedURL "${{ inputs.NPM_FEED_URL }}" -NPMPublishFeedURL "${{ inputs.NPM_PUBLISH_FEED_URL }}" -NPMFeedUser "${{ inputs.NPM_FEED_USER }}" -NPMFeedPwd "${{ inputs.NPM_FEED_PWD }}" -NPMFeedEmail "${{ inputs.NPM_FEED_EMAIL }}" -Path "${{ inputs.Path }}"
      shell: |
        pwsh -noninteractive -command "try {{ $ErrorActionPreference='Stop'; . '{0}' }} catch {{ Write-Error ""FAILED: $_""; throw; }} if ((Test-Path -LiteralPath variable:\LASTEXITCODE)) {{ exit $LASTEXITCODE }}"