name: 'Fix NuGet Feeds'
description: 'Fix NuGet feeds by running a PowerShell script.'
author: 'Mike Burgess'
inputs:
  NUGET_PUBLISH:
    description: 'NuGet Publish setting.'
    required: true
  NUGET_SOURCE:
    description: 'NuGet Source setting.'
    required: true
  NUGET_LIBRARY:
    description: 'NuGet Library setting.'
    required: true
  PROGET_API_KEY:
    description: 'API key for NuGet.'
    required: true
runs:
  using: 'composite'
  steps:
    - run: |
        ..\..\..\scripts\set-nugetfeeds.ps1 -nugetPublish ${{ inputs.NUGET_PUBLISH }} -nugetSource ${{ inputs.NUGET_SOURCE }} -nugetLibrary ${{ inputs.NUGET_LIBRARY }} -nugetApiKey ${{ inputs.PROGET_API_KEY }} -nugetConfigFullPath "${{ github.workspace }}\nuget.config"
      shell: |
        pwsh -noninteractive -command "try { $ErrorActionPreference='Stop'; . '{0}' } catch { Write-Error ""FAILED: $_""; throw; } if ((Test-Path -LiteralPath variable:\LASTEXITCODE)) { exit $LASTEXITCODE }"
