name: 'Fix NuGet Feeds'
description: 'Fix NuGet feeds by running a PowerShell script.'
author: 'Mike Burgess'
inputs:
  NUGET_PUBLISH:
    description: 'NuGet Publish setting.'
    required: true
  NUGET_SOURCE:
    description: 'NuGet Source setting.'
    required: true
  NUGET_LIBRARY:
    description: 'NuGet Library setting.'
    required: true
  PROGET_API_KEY:
    description: 'API key for NuGet.'
    required: true
runs:
  using: 'composite'
  steps:
    - name: test then run set-nugetfeeds.ps1
      run: |
        write-output "test-path of relative path"
        test-path ${{ github.action_path }}/../../../Powershell/Scripts

        write-output "setting location"
        set-location ${{ github.action_path }}/../../../Powershell/Scripts

        write-output "doing a GCI"
        get-childitem .\

        write-output "doing a test-path on the .\set-nugetfeeds.ps1"
        test-path .\set-nugetfeeds.ps1

#        write-output "trying run on set-nugetfeeds.ps1
#        .\set-nugetfeeds.ps1 -nugetPublish "${{ inputs.NUGET_PUBLISH }}" -nugetSource "${{ inputs.NUGET_SOURCE }}" -nugetLibrary "${{ inputs.NUGET_LIBRARY }}" -nugetApiKey "${{ inputs.PROGET_API_KEY }}" -nugetConfigFullPath "${{ github.workspace }}\nuget.config"
      shell: pwsh