#example use

# jobs:
#   example_job:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2  # This is a built-in action from GitHub

#       - name: Use composite action from external repository
#         uses: username/my-action@main  # Replace 'username' with the actual username and 'my-action' with the name of the repository containing your composite action

# example of specific script:

# name: Example Workflow

# on:
#   push:
#     branches:
#       - main

# jobs:
#   example_job:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Fix NuGet Feeds
#         uses: username/fix-nuget-feeds@main
#         with:
#           NUGET_PUBLISH: 'your_publish_value'
#           NUGET_SOURCE: 'your_source_value'
#           NUGET_LIBRARY: 'your_library_value'
#           PROGET_API_KEY: ${{ secrets.PROGET_API_KEY }}

name: 'Fix NuGet Feeds'
description: 'Fix NuGet feeds by running a PowerShell script.'
author: 'Your Name'
inputs:
  NUGET_PUBLISH:
    description: 'NuGet Publish setting.'
    required: true
  NUGET_SOURCE:
    description: 'NuGet Source setting.'
    required: true
  NUGET_LIBRARY:
    description: 'NuGet Library setting.'
    required: true
  PROGET_API_KEY:
    description: 'API key for NuGet.'
    required: true
runs:
  using: 'composite'
  steps:
    - run: |
        .\scripts\set-nugetfeeds.ps1 -nugetPublish ${{ inputs.NUGET_PUBLISH }} -nugetSource ${{ inputs.NUGET_SOURCE }} -nugetLibrary ${{ inputs.NUGET_LIBRARY }} -nugetApiKey ${{ inputs.PROGET_API_KEY }} -nugetConfigFullPath "$PWD\nuget.config"
      shell: 
           | pwsh -noninteractive -command "try {{ $ErrorActionPreference='Stop'; . '{0}' }} catch {{ Write-Error ""FAILED: $_""; throw; }} if ((Test-Path -LiteralPath variable:\LASTEXITCODE)) {{ exit $LASTEXITCODE }}"