name: 'Set Branch Variables'
description: 'Set up variables based on branch names'
author: 'Mike Burgess'
inputs:
  BRANCH_NAME:
    description: 'The name of the branch'
    required: true
  NUGET_PUBLISH_OVERRIDE:
    description: 'An optional override if the code is not deploying from cogstate-releases-candidate'
    required: false
  NUGET_PUBLISH_DEV_OVERRIDE:
    description: 'An optional override if the code is not deploying from cogstate-releases-dev'
    required: false
  NUGET_LIBRARY_OVERRIDE:
    description: 'An optional override if the code is not deploying from cogstate-library-nuget-dev'
    required: false
  NUGET_LIBRARY_DEV_OVERRIDE:
    description: 'An optional override if the code is not deploying from cogstate-library-nuget'
    required: false
  NUGET_SOURCE_OVERRIDE:
    description: 'An optional override if the code is not deploying from nuget-dev'
    required: false
  NUGET_SOURCE_DEV_OVERRIDE:
    description: 'An optional override if the code is not deploying from nuget-dev'
    required: false
outputs:
  version:
    description: "version"
    value: ${{ steps.set-vars.outputs.version }}
  build-type:
    description: "build type"
    value: ${{ steps.set-vars.outputs.build-type }}
  build-config:
    description: "build config"
    value: ${{ steps.set-vars.outputs.build-config }}
  nuget-publish:
    description: "nuget publish feed"
    value: ${{ steps.set-vars.outputs.nuget-publish }}
  nuget-source: 
    description: "nuget source feed"
    value: ${{ steps.set-vars.outputs.nuget-source }}
  nuget-library: 
    description: "nuget library feed"
    value: ${{ steps.set-vars.outputs.nuget-library }}

runs:
  using: 'composite'
  steps:
    - uses: KyoriPowered/action-regex-match@v3
      id: branch-regex
      with:
        text: ${{ inputs.BRANCH_NAME }}
        regex: '(?:.+?)?(?:(?:feature|release)\/(\d+\.\d+\.\d+))\/?([?a-zA-Z]+-\d+)?$'

    #Set the Dev variables if the branch contains feature

    - name: Set dev varaibles
      id: set-dev-variables
      if: contains(inputs.BRANCH_NAME,'feature')
      run: |
       Write-Output $("BUILD_TYPE=dev").tolower() | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
       Write-Output $("BUILD_TYPE=Debug").tolower() | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
       Write-Output $("NUGET_PUBLISH=https://proget.cogstate.com/nuget/cogstate-releases-dev/").tolower() | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
       Write-Output $("NUGET_SOURCE=https://proget.cogstate.com/nuget/nuget-dev/").tolower() | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
       Write-Output $("NUGET_LIBRARY=https://proget.cogstate.com/nuget/cogstate-library-nuget-dev/").tolower() | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      shell: pwsh

    - name: Set dev version
      id: set-dev-version
      if: contains(inputs.BRANCH_NAME,'feature')
      run: |
       Write-Output $("preversion=${{ steps.branch-regex.outputs.group1 }}-${{ env.BUILD_TYPE }}.${{ steps.branch-regex.outputs.group2 }}.${{ github.run_number }}${{ github.run_attempt }}").tolower() | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      shell: pwsh

    #Set the RC Variables if the branch contains release

    - name: Set rc variables
      id: set-rc-variables
      if: contains(inputs.BRANCH_NAME,'release')
      run: |
       Write-Output $("BUILD_TYPE=rc").tolower() | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append   
       Write-Output $("BUILD_CONFIG=Release").tolower() | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
       Write-Output $("NUGET_PUBLISH=https://proget.cogstate.com/nuget/cogstate-releases-candidate/").tolower() | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
       Write-Output $("NUGET_SOURCE=https://proget.cogstate.com/nuget/nuget-dev/").tolower() | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
       Write-Output $("NUGET_LIBRARY=https://proget.cogstate.com/nuget/cogstate-library-nuget/").tolower() | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      shell: pwsh

    - name: Set rc version
      id: set-rc-version
      if: contains(inputs.BRANCH_NAME,'release')
      run: |
       Write-Output $("preversion=${{ steps.branch-regex.outputs.group1 }}-${{ env.BUILD_TYPE }}.${{ github.run_number }}${{ github.run_attempt }}").tolower() | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      shell: pwsh

    #Override the publish variables if they are provided as inputs

    - name: Override Nuget Publish
      id: override-nuget-publish
      if: inputs.NUGET_PUBLISH_OVERRIDE && contains(inputs.BRANCH_NAME,'release')
      run: |
       Write-Output $("NUGET_PUBLISH=${{ inputs.NUGET_PUBLISH_OVERRIDE }}").tolower() | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      shell: pwsh

    - name: Override Nuget Dev Publish
      id: override-nuget-dev-publish
      if: inputs.NUGET_PUBLISH_DEV_OVERRIDE && contains(inputs.BRANCH_NAME,'feature')
      run: |
       Write-Output $("NUGET_PUBLISH=${{ inputs.NUGET_PUBLISH_DEV_OVERRIDE }}").tolower() | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      shell: pwsh

    #Override the Nuget Library variables if they are provided as inputs

    - name: Override Nuget Library
      id: override-nuget-library
      if: inputs.NUGET_LIBRARY_OVERRIDE && contains(inputs.BRANCH_NAME,'release')
      run: |
       Write-Output $("NUGET_LIBRARY=${{ inputs.NUGET_LIBRARY_OVERRIDE }}").tolower() | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      shell: pwsh

    - name: Override Nuget Dev Library
      id: override-nuget-dev-library
      if: inputs.NUGET_LIBRARY_DEV_OVERRIDE && contains(inputs.BRANCH_NAME,'feature')
      run: |
       Write-Output $("NUGET_LIBRARY=${{ inputs.NUGET_LIBRARY_DEV_OVERRIDE }}").tolower() | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      shell: pwsh

    #Override the Nuget Source variables if they are provided as inputs

    - name: Override Nuget Source
      id: override-nuget-source
      if: inputs.NUGET_SOURCE_OVERRIDE && contains(inputs.BRANCH_NAME,'release')
      run: |
       Write-Output $("NUGET_SOURCE=${{ inputs.NUGET_SOURCE_OVERRIDE }}").tolower() | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      shell: pwsh

    - name: Override Nuget Dev Source
      id: override-nuget-dev-source
      if: inputs.NUGET_SOURCE_DEV_OVERRIDE && contains(inputs.BRANCH_NAME,'feature')
      run: |
       Write-Output $("NUGET_SOURCE=${{ inputs.NUGET_SOURCE_DEV_OVERRIDE }}").tolower() | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      shell: pwsh

    - name: Set output variables
      id: set-vars
      run: |
       Write-Output $("version=${{ env.preversion }}").tolower() | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
       Write-Output $("build-config=${{ env.BUILD_CONFIG }}").tolower() | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
       Write-Output $("build-type=${{ env.BUILD_TYPE }}").tolower() | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
       Write-Output $("nuget-publish=${{ env.NUGET_PUBLISH }}").tolower() | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
       Write-Output $("nuget-source=${{ env.NUGET_SOURCE }}".tolower() | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
       Write-Output $("nuget-library=${{ env.NUGET_LIBRARY }}".tolower() | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
      shell: pwsh
